version: '3'

services:
  webhook:
    build: .
    command: npx nodemon src/index.js --watch src
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/alice
      - node_modules_volume:/alice/node_modules

  ngrok:
    image: wernight/ngrok
    command: ngrok http --region=eu webhook:${PORT}
    ports:
      - 4040:4040

volumes:
  node_modules_volume:
